// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core_dart/firebase_core_dart.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANXu9fzEStxq9xEllPyO1JYKvTpOX0sUY',
    appId: '1:410973684247:android:f09242766520f9fe68d252',
    messagingSenderId: '410973684247',
    projectId: 'mausvpn-5c579',
    storageBucket: 'mausvpn-5c579.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPYZD89uEld_oLlBi9t5lIWUlIrPnXiZk',
    appId: '1:410973684247:ios:da89fa67baef781f68d252',
    messagingSenderId: '410973684247',
    projectId: 'mausvpn-5c579',
    storageBucket: 'mausvpn-5c579.appspot.com',
    iosBundleId: 'net.appdevs.suppervpn',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6DnqE27c9TjvdtOT_c6eROn8omqrL8BI',
    appId: '1:410973684247:web:8d0c60e93f95035268d252',
    messagingSenderId: '410973684247',
    projectId: 'mausvpn-5c579',
    authDomain: 'mausvpn-5c579.firebaseapp.com',
    storageBucket: 'mausvpn-5c579.appspot.com',
    measurementId: 'G-XQZ6XNCHLL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPYZD89uEld_oLlBi9t5lIWUlIrPnXiZk',
    appId: '1:410973684247:ios:8b4ec891836954de68d252',
    messagingSenderId: '410973684247',
    projectId: 'mausvpn-5c579',
    storageBucket: 'mausvpn-5c579.appspot.com',
    iosBundleId: 'com.nagakaburos.mausvpn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6DnqE27c9TjvdtOT_c6eROn8omqrL8BI',
    appId: '1:410973684247:web:30b95d10ca93dd5b68d252',
    messagingSenderId: '410973684247',
    projectId: 'mausvpn-5c579',
    authDomain: 'mausvpn-5c579.firebaseapp.com',
    storageBucket: 'mausvpn-5c579.appspot.com',
    measurementId: 'G-1PQECPM5NF',
  );

}